name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Dependencies
      run: msbuild AtlasToolbox-WinUI3.sln /t:restore /p:Platform="x64"

    - name: Build Solution
      run: msbuild AtlasToolbox-WinUI3.sln /p:Configuration=Release /p:Platform="x64"

    - name: Compile .ISS to .EXE Installer
      uses: robin24/inno-setup-action@v1
      with:
        filepath: ${{ github.workspace }}\Installer\setup.iss

    - name: Create ZIP of Installer
      run: powershell Compress-Archive -Path "${{ github.workspace }}\Installer\Output\*" -DestinationPath "${{ github.workspace }}\PCToolsToolbox.zip"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PCToolsToolbox
        path: ${{ github.workspace }}\PCToolsToolbox.zip
